### ISSUE TITLE
[UniProt] new API silently breaks gapseq_find

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [jotech/gapseq#128]
FYI, I created an issue [#275](https://github.com/ebi-uniprot/uniprot-rest-api/issues/275) with UniProt explaining how the new UniProt website & REST API breaks `uniprot.sh` 's querying of UniRef. This may go unnoticed for users of gapseq, since now queries just return immediate empty results and gapseq will only use the stored sequences installed through `update_sequences.sh`.

The queries still work on the [legacy UniProt server](https://legacy.uniprot.org), but this requires patching of `uniprot.sh` and this access will be discontinued with the next UniProt 2022_03 release.

**Comment by Waschina** [comment]
Thank you very much for pointing out this issue.

With the commit 82ff4ad1c5c5f9c2bba17693b7e43ee8839330c4 we should have a working sequence download again. It works in three steps:
1. Find UniprotKB IDs of query-matching proteins
2. Match IDs/Accessions from (1) to identity-based protein clusters (UniRef)
3. Retrieve representative Sequences of protein clusters

Unfortunately, the second step takes way too long when step 1 results in like 10 000+ hits, in part because we currently use GET in batches to find the matching UniRef cluster IDs as suggested in the issue [#275](https://github.com/ebi-uniprot/uniprot-rest-api/issues/275) you created.

I've just found out that there is a POST option with Uniprot REST for ID matching: https://www.uniprot.org/help/id_mapping
We will try that option, too, and hope that this works faster.

Thanks again
Silvio

**Comment by Waschina** [comment]
Hi,

Just as an update: I have locally implemented a POST-based mapping von uniprot accessions to UniRef50/90. When testing, the POST-version was actually slower than the the GET method, that we currently have in gapseq.

I'll think about another approach...

**Comment by Waschina** [comment]
Uniprot queries and downloads should now be optimized and much faster.
