### ISSUE TITLE
gapseq adapt - No reactions can be added

### ISSUE THREAD

**Issue by shraddhakhirwadkar** [jotech/gapseq#160]
./![image](https://user-images.githubusercontent.com/73715781/216721283-a5dc1d31-37e1-4abc-b7ed-9feb3485c6f4.png)
Hi, 
When I try to add the reaction rxn09984 (ModelSEED), I get an error saying "Reactions not in gapseq database:rxn09984. No reactions can be addded. Execution halted" I have already done the following modifications for the model to use cpd02271 which rxn09984 uses with:
./gapseq adapt -m /home/shraddha/gapseq/bin.7.orig-draft.RDS -w cpd02271:TRUE -c /home/shraddha/gapseq/bin.7.orig-rxnWeights.RDS -g /home/shraddha/gapseq/bin.7.orig-rxnXgenes.RDS -b /home/shraddha/gapseq/bin.7.orig-all-Reactions.RDS

However, only EX_cpd02271_e0 is added, and not rxn09984 which actually hydrolyses cpd02271. How do I succesfully add rxn09984? Or does the presence of EX_cpd02271_e0 alone ensure the consumption of the compound?
Thank you for your help in advance.

**Comment by jotech** [comment]
Hi @shraddhakhirwadkar 

You are right; it is not working, Thanks for reporting! The reason is that the reaction rxn09984 is not yet part of the gapseq reaction database.
Although this could be fixed quickly, I am wondering how the reaction could be linked in the metabolic model because, at least from what I can see in the [modelseed reaction database](https://modelseed.org/biochem/compounds/cpd02271 ) (on which gapseq builds), galactose oligosaccharide is not produced by any other reaction and seems to be a dead end.
Do you expect galactose oligosaccharide to be present in the environment? Is a transporter needed, or is the enzyme operating in the periplasm or extracellularly? 
It would be great to clarify this to link the reaction to a functional model properly.

**Comment by Waschina** [comment]
@jotech: I agree. Reactions with cpd02271 are excluded from the database because the compound is generic (unclear how many galactose subunits). A better solution would include a galactose oligosaccharide (GOS) prototype with a fixed number of units and molecular formula. A good number of units for GOS is between 3 and 10.

**Comment by shraddhakhirwadkar** [comment]
@jotech thank you for your prompt reply. I wanted to add the reaction to metabolize GOS in Bifidobacterium metabolic models. GOS is used as a prebiotic for infants to promote gut microbiome stability. From reference 1:
![image](https://user-images.githubusercontent.com/73715781/217054932-d5fc7556-b71d-4866-a7f8-fb294eca5cf8.png)


GalA (cell-membrane bound endogalactanase) degrades galactan and releases a galactotriose. The galactotriose is then imported into the cell through an ABC transporter (GalCDE) and hydrolyzed by GalG. As @Waschina mentioned a good number of units for GOS is between 3-10 (more between 3-8). Additional info in Reference 2.

Thank you so much for your help. Please let me know if I can provide any additional information. Can you please let me know when the reaction is added to the database?

Reference:
1) Hinz, S. W., Pastink, M. I., van den Broek, L. A., Vincken, J. P., & Voragen, A. G. (2005). Bifidobacterium longum endogalactanase liberates galactotriose from type I galactans. Applied and environmental microbiology, 71(9), 5501-5510.
2) Goh, Y. J., & Klaenhammer, T. R. (2015). Genetic mechanisms of prebiotic oligosaccharide metabolism in probiotic microbes. Annual review of food science and technology, 6, 137-156.

**Comment by Waschina** [comment]
I just checked. You could try to add this reaction instead:

**rxn07043**: (1) Galactan[e] + (1) H2O[e] ––> (2) Galactose[e]

It's a 2-unit "galactan", which is degraded to the galactose units extracellularly. 

The ID for Galactan for the gap-fill medium is cpd12777

**Comment by jotech** [comment]
I think, ecologically speaking, these two versions are quite different. The one using the ABC transporter is hydrolyzing Galactan intracellular, and rxn07043 does in the extracellular space. It could make quite a difference when it comes to interactions (common vs. private good).
