### ISSUE TITLE
Errors in HPC cluster

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#17]
Dear All,

I would like to report some errors arisen while I was running 6 instances of GapSeq in my HPC cluster. In each instance that was the error output:
```
Warning: [tblastn] Query_1 UniRef50_O30642 M.. : One or more O characters replaced by X for alignment score calculations at positions 201 
Warning: [tblastn] Query_1 UniRef90_Q18TV3 T.. : One or more O characters replaced by X for alignment score calculations at positions 330 
grep: invalid option -- 'g'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: invalid max count
index file AEP.fna.tmp.fai not found, generating...
```
Only the last line seems to be not problematic...
Please be aware that the pipeline ended successfully.
I will try to repeat the pipeline with the myb71.fna file and I will return.

Kind Regards,
Georgios

**Comment by maringos** [comment]
For MYB71:

```
Warning: [tblastn] Query_1 UniRef50_O30642 M.. : One or more O characters replaced by X for alignment score calculations at positions 201 
Warning: [tblastn] Query_1 UniRef90_Q18TV3 T.. : One or more O characters replaced by X for alignment score calculations at positions 330 
grep: invalid option -- 'g'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: invalid max count
index file myb71.fna.tmp.fai not found, generating...
```

**Comment by Waschina** [comment]
I have the same warnings when performing gapseq on the cluster. My guess is thats it's the version of 'grep'.

```
Warning: [tblastn] Query_1 UniRef50_O30642 M.. : One or more O characters replaced by X for alignment score calculations at positions 201 
Warning: [tblastn] Query_1 UniRef90_Q18TV3 T.. : One or more O characters replaced by X for alignment score calculations at positions 330 
grep: invalid option -- 'g'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: invalid max count
```

**Comment by jotech** [comment]
if still relevant, please repoen

**Comment by Waschina** [comment]
Concerning the first two warnings:
"O" is a one-letter code for the rare amino acid "Pyrrolysine" - which occurs in some methanogenic archaea and bacteria. tblastn cannot handle this amino acids and replaces is with X (any amino acid). Thus, it's not an issue for the gapseq procedures.

**Comment by songweizhi** [comment]
Hi, 
Thanks for figuring out the cause of the  "O characters" issue.
Besides this, I also saw a list of "No such file or directory", "Broken pipe" and 'xrealloc' related errors when running GapSeq against the default pathway databses on our HPC, please see some examples below:

```
cat: /srv/scratch/z5039045/Softwares/gapseq/src/../dat/seq/Bacteria/rxn/Q84N56.fasta: No such file or directory
rm: cannot remove ‘/srv/scratch/z5039045/Softwares/gapseq/src/../dat/seq/Bacteria/rxn/Q84N56.fasta’: No such file or directory
cat: /srv/scratch/z5039045/Softwares/gapseq/src/../dat/seq/Bacteria/rxn/Q4KM86.fasta: No such file or directory
rm: cannot remove ‘/srv/scratch/z5039045/Softwares/gapseq/src/../dat/seq/Bacteria/rxn/Q4KM86.fasta’: No such file or directory
sort: write failed: standard output: Broken pipe
sort: write error
...
/srv/scratch/z5039045/Softwares/gapseq/src/gapseq_find.sh: line 457: [: /srv/scratch/z5039045/Softwares/gapseq/src/../dat/seq/Bacteria/rev/2.7.7.13: binary operator expected
/srv/scratch/z5039045/Softwares/gapseq/src/gapseq_find.sh: line 461: [: /srv/scratch/z5039045/Softwares/gapseq/src/../dat/seq/Bacteria/unrev/2.7.7.13: binary operator expected
...
/srv/scratch/z5039045/Softwares/gapseq/src/gapseq_find.sh: xrealloc: cannot allocate 18446744072358002816 bytes (45252608 bytes allocated)
sort: fflush failed: standard output: Broken pipe

```
Although I saw these errors, I can still get the Pathways.tbl and Reactions.tbl at the end of the run.

The "xrealloc: cannot allocate" error might due to the low amount of memory (10Gbp) I requested in my job script. is GapSeq memory intensive? will this affect the prediction results in the two final output tables?
 
Do you have any idea why the "No such file or directory" and "Broken pipe" error occurred? I have about 30 job scripts running simultaneously in our HPC, could this be the reason?

 I haven't seen any temporary files in the directory where I executed gapseq. Where do you store the temp files (if any)? Does this due to the overwriting/removing of the temp files among different job scripts? 

Thanks,
Weizhi

**Comment by jotech** [comment]
Hi Weizhi,
sorry I overlooked you reply because this issue was already closed!

I could replicate the 'cat' and 'rm' errors and tried to fix it with the last commit.
It was related to a plant-specific pathway for which specific gene sequences are available but not for bacteria.

Maybe you may want to exclude non-bacterial pathways from your analysis, this could be faster and avoid pathways that are phylogenetically not expected. It can be done by
``./gapseq find -m bacteria ...``

Concerning the memory allocation error, it's a bit strange. I usually have memory usage of 500mb-2gb.
But it depends, may I ask what your input genome sequence is and how big it is in size?

**Comment by jotech** [comment]
0a5b82b2d7c1fbf0c0f03f6fcc3ab02d01d4a463

**Comment by jotech** [comment]
please reopen if still relevant
