### ISSUE TITLE
alternative transporters

### ISSUE THREAD

**Issue by jotech** [jotech/gapseq#21]
During transporter search, it can happen that not candidate reaction is found for a certain transporter type. In this case, an alternative transporters can be used (i.e.: a different transporter type). Up to now, this alternatives were not listed in *-Transporter.tbl (only in *-Transporter.lst).

The question is, how to handle alternative transporters, should they be included?

**Comment by Waschina** [comment]
Unfortunately, there's a malformatting of the results table since the commit. Example for issue reproduction:

`./transporter.sh -b 200 GCF_000389635.1_ASM38963v1_genomic.fna.gz`

In the output file `GCF_000389635.1_ASM38963v1_genomic-Transporter.tbl` the line #795 is corrupt. It misses the first column. All subsequent columns are in column n-1.

Example genome:
[GCF_000389635.1_ASM38963v1_genomic.fna.gz](https://github.com/jotech/gapseq/files/3534533/GCF_000389635.1_ASM38963v1_genomic.fna.gz)

**Comment by jotech** [comment]
should be better now :) ?
