### ISSUE TITLE
Gapfilling occasionally fails silently with GLPK

### ISSUE THREAD

**Issue by cdiener** [jotech/gapseq#228]
Hi Gapseq Team,

During the reconstruction of some larger strain databases we noticed that the medium gapfilling will usually fail for a few assemblies. In general, we observe the following 2 behaviors:

## Fail loud (example 1)

For some models `gapseq fill` will fail in the gapfilling step with an error

```
Loading required package: glpkAPI
using GLPK version 5.0
Warning message:
glpkAPI is used but cplexAPI is recommended because it is much faster 
Error in gapfill4(mod.orig = mod.orig, mod.full = mod, rxn.weights = copy(rxn.weights),  : 
  Final model cannot grow. Something is terribly wrong!
```

## Fail silently (example 2)

Maybe more problematic is that sometimes `gapseq fill` will report success, but the resulting model can not grow.

```
[...]
Filled components:     1 ( Citrate-e0 )
Added reactions:       5 
Final growth rate:     0  # <-- 
[...]
``` 

The produced models are usually infeasible on any non-zero growth rate, even when opening all exchanges.

## MRP

Here are the relevant input files for both examples: 
[examples.zip](https://github.com/user-attachments/files/16659232/examples.zip)

The used commands are:

```bash
#!/bin/bash -ue
gapseq medium -m example1-draft.RDS -p example1-all-Pathways.tbl -o medium.csv
gapseq fill -m example1-draft.RDS -n medium.csv -c example1-rxnWeights.RDS -b 100 -g example1-rxnXgenes.RDS > example1.log
```

Same commands for example 2.

All was run in gapseq docker container [from here](https://hub.docker.com/repository/docker/cdiener/gapseq/general).

**Comment by cdiener** [comment]
Some more info: 

For the silent fail I sometimes see the error:

```
Warning in gapfill4(mod.orig = mod.orig, mod.full = mod, rxn.weights = copy(rxn.weights),  :
  Final model MGYG000003531 cannot produce enough target even when all candidate reactions are added! obj=0 lp_stat=5
```

This seems to affect mostly Archaea models. For instance, for UHGG Archaea assemblies 25/28 will show this error and fail silently.

**Comment by Waschina** [comment]
Hi @cdiener 

since we are currently working on a new gapseq release, where the dependencies on the R-packages "sybil", "glpkAPI", "sybilSBML" are all replaced with ["cobrar"](https://github.com/Waschina/cobrar), I have tested the two examples with the latest dev version of the [gapseq "cobrar" branch](https://github.com/jotech/gapseq/tree/cobrar).
In both cases, the gap-filling worked as expected and without errors or warnings. I guess, the gapfill issue you report is somehow related to "glpkAPI" and I'm still trying to understand why this is happing. In any case, the problem does not seem to persist in the upcoming gapseq release.

**Comment by cdiener** [comment]
Okay, I will do a docker image based on the devel branch and see if it fixes the issue from our side.

**Comment by Waschina** [comment]
That is a good idea! I'll try to implement it this week.
  
Feel free to let me know if you experience any issues with the cobrar branch; ideally, installation is more straightforward.

**Comment by Waschina** [comment]
The gapfill fails were related to LP scaling in GLPK. By default, sybil won't trigger LP scaling. So in some instances (and in the two examples above) the returned fluxes by GLPK were outside the flux bounds due to number representation inaccuracies. For instance a flux of -1e-10 might be returned for a reaction with a lower bound of 0.
The solution was to explicitly trigger LP scaling when performing FBA.

I have tested the two examples from above, but not the UHGG Archaea cases. Please re-open, if the issue remains for other cases.

**Comment by cdiener** [comment]
Thanks, will try it now. FYI I tried with the cobrar branch too but gapfilling failed because of missing the sybil package which is still imported by gfSuite.R.

```
glpk is used as LP solver but cplex is recommended because it is much faster. If you have IBM's ILOG cplex installed, you can add cplex-support to gapseq by installing the R-package 'cobarCPLEX' (https://github.com/Waschina/cobrarCPLEX). 
Loading model files /data/example1-draft.RDS 
Loading required package: sybil
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘sybil’
Error in .requirePackage(package) : 
  unable to find required package ‘sybil’
Calls: add_missing_diffusion ... .findInheritedMethods -> getClass -> getClassDef -> .requirePackage
Execution halted
```

**Comment by cdiener** [comment]
FYI, I also tried the cobrar branch, but for me gapfilling fails because it is still importing sybil somewhere:

```
glpk is used as LP solver but cplex is recommended because it is much faster. If you have IBM's ILOG cplex installed, you can add cplex-support to gapseq by installing the R-package 'cobarCPLEX' (https://github.com/Waschina/cobrarCPLEX). 
Loading model files /data/example1-draft.RDS 
Loading required package: sybil
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘sybil’
Error in .requirePackage(package) : 
  unable to find required package ‘sybil’
Calls: add_missing_diffusion ... .findInheritedMethods -> getClass -> getClassDef -> .requirePackage
Execution halted
```

**Comment by Waschina** [comment]
sybil should not be used in `gf.suite.R` anymore. Could it be that your draft metabolic network "example1-draft.RDS" was generated using a gapseq version that still used sybil? In that case, the object in the RDS file is a sybil-object and R will try to load the required package. If this is the case, you could simple re-run the gapseq draft module to update the draft network.

**Comment by cdiener** [comment]
Oh okay, that makes sense then. I will try to redraft.
