### ISSUE TITLE
awk: illegal primary in regular expression +-NEOMENTHOL-DEHYDROGENASE-RXN at -NEOMENTHOL-DEHYDROGENASE-RXN

### ISSUE THREAD

**Issue by cskaandorp** [jotech/gapseq#37]
Hi, 

I am no expert in the field, merely a programmers that's using this package to get things done. I have already ran `gapseq doall` on 10 different genome files and have run each time into the following warning / error:

awk: illegal primary in regular expression +-NEOMENTHOL-DEHYDROGENASE-RXN at -NEOMENTHOL-DEHYDROGENASE-RXN
 input record number 1, file 
 source line number 1

Should I worry about this? The script finishes, but I don't understand if I have missed data due to this problem. Thanks.

Cspr

**Comment by Waschina** [comment]
thanks for pointing out this error message. It's caused because _awk_ interprets the "+" in this specific reaction name as a regular expression symbol and not as part of the reaction's name. It does affect only a pathway (menthol biosynthesis), which should anyway not be predicted for bacteria or archaea. Thus, you do not need to worry about it as it does not affect the model/gapseq output.

However, we aim to correct the causes of this error in one of the following commits.

Best
Silvio
