### ISSUE TITLE
Error in BacArena after loading model generated after gapfilling with LB media

### ISSUE THREAD

**Issue by hites77** [jotech/gapseq#43]
Following error got popped up when model was loaded in bacArena. (The gapfilling of model was done with LB supplemented glucose. )

"Median lower bound for non-zero and non-Inf exchanges is:**06**"
Warning message in Organism(model = model, ...):
"Many lower bounds of of the model seems to be set to non -infinity. Please be aware that they will be used as maximal uptake rates even when the available medium is more abundant! (set setAllExInf=TRUE to reset all exchanges to -INF)"

When I used LB media without glucose  for gapfiling then the notification was

"Median lower bound for non-zero and non-Inf exchanges is:**-16**"
Warning message in Organism(model = model, ...):
"Many lower bounds of of the model seems to be set to non -infinity. Please be aware that they will be used as maximal uptake rates even when the available medium is more abundant! (set setAllExInf=TRUE to reset all exchanges to -INF)"

This error was not observed when model gapfilling was done with minimal media.
Here it shows
"Median lower bound for non-zero and non-Inf exchanges is:**-1006**"

How to solve this issue

**Comment by jotech** [comment]
actually this is a warning and not an error, isn't it :D ?!

The point in BacArena is that it is not clear whether the lower bounds are set as default diet or maximum uptake rates.
For example, a value of -10 in the glucose exchange EX_cpd00027_e0 could be due to the diet or due to the transporter kinetics.
The diet constraints are given by the environment in BacArena (``addSubs()``) but if there should be any limit of the uptake rates this would overrule the environmental diet constraints.

When adding a model in BacArena, this could not be determined automatically. 
This is why a warning is printed but it is not an error!

If you do not have transporter uptake rates set (as it is the case for gapseq models), then it is recommended to use ``setAllExInf=TRUE`` when creating the organism in BacArena. In this case, only environmental diet constraints are used.

**Comment by hites77** [comment]
Thanks, Yupp that was warning, using setAllExInf=TRUE eliminates warning. 
But what exactly the Median lower bound values means as changing the gapfill media changes its value and -1006 seems to be most common value.

**Comment by jotech** [comment]
sure this is a crucial point and that is why the warning is printed.
In the past, quite some models used this transporter uptake limit to define maximum uptake rates and other exchange reactions were unconstrained. We tried to pay attention to this and integrated maximum uptake rates as default behavior in bacarena.
But I agree that from a gapseq perspective, this makes things a bit complicate.

**Comment by hites77** [comment]
So is there way to optimize this uptake rates and metabolite transport fluxes (either in sybil or in cobratoolbox) so that we can accurately predict the exchange of metabolites between two bacteria ? Can exchange of molecules which are in less concentration like vitamins or siderophores can be predicted , because I observe that mostly high concentration moelcule like acetate and formate are reported to be exchanged and even I observed it. The paper "Microbial Community Metabolic
Modeling: A Community Data-Driven Network Reconstruction" by Christopher et al , seems to talk about exchange of wide range of metabolites but they have considered the compartmentalized model system.

**Comment by jotech** [comment]
This should definitely be possible and was already done with BacArena several times (for example https://doi.org/10.1038/s41396-019-0504-y bacarena was used to model the crossfeeding of sucrose between _Ochrobactrum_ and _Pseudomonas_).
I talked with Eugen, we changed the default behavior so that exchange reactions are constrained by the medium only (by default).
Please check out the latest BacArena after the commit: https://github.com/euba/BacArena/commit/29620bef46ea1edb5b2c25bf072218cd706c3209
Concerning siderophores, I'm not sure whether genome-scale metabolic modeling which often optimized biomass production can correctly predict this correctly.
Does it makes sense to you?

**Comment by hites77** [comment]
Thanks, I will check it and if any issue occur I will post it.
