### ISSUE TITLE
Installation and usage procedure suggestions

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [jotech/gapseq#55]
Hi,

Thanks for your work on gapseq, it looks like a very useful tool. I'm currently trying to dockerize the tool to play around with it a bit and have some suggestions:

1. It would be useful to have an install command that will download the requisite data files for bacterial and archaea. as of now, I think I have to manually run a random genome through the script to trigger database downloads.
2. Being able to specify the kingdom (bacteria/archaea) with doall would be good. Or will this be automatically inferred during model construction?

Please let me know if this is unclear!

**Comment by jotech** [comment]
Hi, thanks for your suggestions!
A database update could be triggered by by calling ``./src/update_sequences.sh``. 
And yes, ``gapseq find`` can detect whether a genome of a bacterium or an archaeum is given. The automatic detection is based on 16S and is available by  ``gapseq find -t auto``. But I also changed the default setting of ``gapseq doall`` so that by now you can directly select it: ``gapseq doall Bacteria`` (or: Archaea). If nothing is selected, then the default is auto detection!
Can this work the way you suggested?

**Comment by jdwinkler-lanzatech** [comment]
Ah yes, perfect. I didn't see a way to do that with the doall command so that'll work nicely. Thanks for your help!

**Comment by jotech** [comment]
cool! If any problems occur feel free to re-open the issue :)
