### ISSUE TITLE
Question about gene identifiers

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [jotech/gapseq#71]
Hi again,

I'm trying to cross-reference annotations I've generated for assembly proteomes to the gene identifiers generated by gapseq. It looks like the gene name is just <contig fasta id>_<region_start>_<region_end>. (I recognize that these may or may not be actual ORFs based on how tblastn works, of course). Is my interpretation correct?

It might actually be nice to supply a GFF file with called ORFs from Prodigal/Glimmer/etc and have the tblastn-inferred regions mapped automatically to avoid having to switch over to using proteome-derived calls. I saw your reasoning on issue #64 on that matter and it makes sense.

**Comment by Waschina** [comment]
Hi,
gapseq runs on the genome sequence alone without the need for an annotation file; thus gapseq defined it's own identifiers of genes by saving the region of the gene in the genome sequence. The format is:

**<contig_id>**_**<region_start>:<region_end>**
(e.g.: NC_009614.1_3261277:3262974)


This notion has the advantage that one can directly go back to their genome viewers of choice (e.g. here for [NC_009614.1_3261277:3262974](https://www.ncbi.nlm.nih.gov/nuccore/150002608?report=graph&tracks=[key:sequence_track,name:Sequence,display_name:Sequence,id:STD649220238,annots:Sequence,ShowLabel:false,ColorGaps:false,shown:true,order:1][key:gene_model_track,name:Genes,display_name:Genes,id:STD3194982005,annots:Unnamed,Options:MergeAll,CDSProductFeats:false,NtRuler:true,AaRuler:true,HighlightMode:2,ShowLabel:true,shown:true,order:7]&assm_context=GCF_000012825.1&v=3258730:3265521&c=CCFFCC&select=null&slim=0)) and map those regions to their own specifc genome annotation file, since users potentially have different annotation file formats.

Best
Silvio

**Comment by jdwinkler-lanzatech** [comment]
Thanks, that's what I figured! I'm basically just mapping gene ids to candidate ORFs based on sequence windows at the moment, which works surprisingly well if you want to cross reference model genes with annotations generated by other pipelines requiring ORF calls (eggNOG, interproscan, Pfam HMMSCAN, etc). Integration is always challenging....

**Comment by Waschina** [comment]
I agree and am glad to hear it works well. Region ends can be a bit fuzzy with gapseq as the regions might not always be framed by start and stop codons, so the mapping to the annotation file should include some tolerance. We will include a paragraph on the gene names in gapseq in the documentation. Thanks for your comment! Others will likely have the same question.

**Comment by jdwinkler-lanzatech** [comment]
Thanks for the help again!
