### ISSUE TITLE
Speed improvement suggestions

### ISSUE THREAD

**Issue by darwinbandoy** [jotech/gapseq#77]
> for bug reports and errors please report the output of: ./gapseq test

Thank you for your work, this is a very move towards genome based metabolic modelling.

For bacterial annotation I use prokka which takes about 5 minutes per genome.  Prokka uses blast and hhmer3. Maybe there something there that can be used here so that pathway and reaction searching does not take 4 hours per genome. Or maybe do some parallelization which can be done with multicore and high RAM capacities.

**Comment by Waschina** [comment]
Hi!
Thank you for the suggestion and for using gapseq :)

We are aware that the runtime is long compared to other tools such as carveme or modelseed. Currently, we are working on a better solution (in terms of runtime), and consider different options; but we cannot promise a date for this enhancement, yet.

When constructing several models, the best solution at the moment is to use the `-k` option in `./gapseq find`, which uses only one CPU per genome, and to start several gapseq reconstruction at the same time e.g. using  GNU parallel (see #52).

**Comment by jotech** [comment]
I completely agree with this and we will have some improvements in the future!
The background for this is that gapseq was made not only for model generation but also pathway analysis and here fine-grained output and step-wise blasting suited well in the beginning.

But let me play the devil's advocate for a moment: parallelization will not necessarily speed up things! 
Usually people reconstruct many organisms at once nowadays and there is no difference in using many cores for one organism or one core for each of several organisms, at least in cases in which the number of cores is smaller than the number of organisms. On a computer cluster, several hundreds of models can be ready in a few hours when starting gapseq for each organism side by side.

**Comment by VadimDu** [comment]
Thank you for the great tool you have developed.

Running in parallel many instances of gapseq for many genomes is of course a good option to speed things up.
But if I understood correctly, the "tblastn" step is running on a single thread? if so it might be one bottleneck for the total running time.

**Comment by jotech** [comment]
hi @VadimDu, thanks for you kind feedback!

You are right the tblastn step is time limiting at the moment. The reason for it is that we do not do a single big blast but a step-wise alignment for each reaction. This was done to actual reduce the amount of necessary alignment because gapseq can stop if a good hit (not necessarily the best one) is found. We did this because we have different sequences databases (uniprot reviewed/unreviewed, metacyc, user-defined) and the protein blast query could easily get quite big...
This has the disadvantage that we we now have to disentangle our code a bit in order to do one single parallelized alignment. 

Nonetheless, It's on our priority list! Up until that time, running many instances should also help a bit, hopefully :)

**Comment by bramvandijk88** [comment]
I wonder if the easiest way to solve this problem isn't to change from blast to diamond? Or at least have an option to switch aligners. I don't think this will disrupt the current flow of the program, as the output of diamon can be like "-outfmt 6" too.

**Comment by nick-youngblut** [comment]
It appears that you don't allow the user to select the number of parallel subprocesses (`parallel --jobs`):

```
cat $q | parallel --gnu --will-cite --block 50k --recstart '>' --pipe tblastn -db orgdb -qcov_hsp_perc $covcutoff -outfmt \'"6 $blast_format"\' -query - > query.blast
```

**Comment by nick-youngblut** [comment]
It could also be helpful to parallelize at Line 446 of `gapseq_find.sh`

```
for i in `seq 1 $pwyNr`
```

...but this may require placing that entire loop in separate script and calling it with `parallel`

**Comment by Waschina** [comment]
With the latest changes, gapseq should be faster. 

Also, gapseq now allows users to specify the number of parallel processes. You can use the Option `-K 4` to use four CPUs for the alignments.

As another speed up option, users can now provide a fasta with pre-determined protein sequences as input instead of the genomic nucleotide fasta. However, please note, that in the protein-fasta case, you will need to manually specify if the genome from a bacterium (`-t Bacteria`) or archaea (`-t Archaea`) in "gapseq find". This is because the automatic taxonomic domain prediction relies on a 16S rRNA gene sequence and/or the nucleotide kmer-distribution. In the same lines, users need to manually specify which biomass reaction reaction should be added to the draft model if a protein fasta is used as input to gapseq. We will work on a solution for automatic domain/biomass prediction that works with both, nucleotide and protein input.

**Comment by gmhhope** [comment]
Hi Johannes,

Your tool is great. Thank you!

I would like to ask for your suggestions on the performance suggestions to speed up the process. I am switching to use `.faa` instead of `.fna` for the `find` step. But still it looks like it will take a lot of time. Just see what can be further optimized. Here is the toy example running script in HPC and its output & performance efficiency.

Thanks for your help! Btw, how to run 100+ strains at the same time and utilize multiple tasks in a single script?

Best,
Minghao

# my playing script
```
#!/bin/bash
#SBATCH --job-name=gapseq_test
#SBATCH --mail-type=BEGIN
#SBATCH --mail-user=...
#SBATCH -p compute
#SBATCH -q batch
#SBATCH -t 48:23:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4G

eval "$(conda shell.bash hook)"

conda activate gapseq-dev

gapseq=/projects/gongm_projects/hpcenv/opt/gapseq/./gapseq
modelA="myb71"

# Reaction & Pathway prediction
$gapseq find -p all -b 200 -m Bacteria -K 24 $modelA.fna.gz 

# Transporter prediction
$gapseq find-transport -b 200 $modelA.fna.gz 

# Building Draft Model - based on Reaction-, Pathway-, and Transporter prediction
$gapseq draft -r $modelA-all-Reactions.tbl -t $modelA-Transporter.tbl -p $modelA-all-Pathways.tbl -c $modelA.fna.gz -u 200 -l 100

# Gapfilling
$gapseq fill -m $modelA-draft.RDS -n TSBmed.csv -c $modelA-rxnWeights.RDS -g $modelA-rxnXgenes.RDS -b 100


```
Job ID: 18459460
Cluster: slurm_cluster
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 32
CPU Utilized: 07:29:41
CPU Efficiency: 4.86% of 6-10:08:32 core-walltime
Job Wall-clock time: 04:49:01
Memory Utilized: 896.56 MB
Memory Efficiency: 0.68% of 128.00 GB
-------------------------------------------------------------
       JobID  User   State    CPUTime Exit     MaxRSS        NodeList  Partition                   ReqTRES              Submit               Start                 End    Elapsed 
------------ ----- ------- ---------- ---- ---------- --------------- ---------- ------------------------- ------------------- ------------------- ------------------- ---------- 
18459460     gongm COMPLE+ 6-10:08:32  0:0                  sumner040    compute billing=32,cpu=32,mem=13+ 2023-04-02T22:57:05 2023-04-02T22:57:07 2023-04-03T03:46:08   04:49:01 
18459460.ba+       COMPLE+ 6-10:08:32  0:0    896.56M       sumner040                                      2023-04-02T22:57:07 2023-04-02T22:57:07 2023-04-03T03:46:08   04:49:01 
18459460.ex+       COMPLE+ 6-10:08:32  0:0      1.58M       sumner040                                      2023-04-02T22:57:07 2023-04-02T22:57:07 2023-04-03T03:46:08   04:49:01 
-------------------------------------------------------------
```

**Comment by gmhhope** [comment]
#### Figure out using job array

```
#!/bin/bash
#SBATCH --job-name=gapseq_faa
#SBATCH --mail-type=BEGIN
#SBATCH -p compute
#SBATCH -q batch
#SBATCH -t 48:23:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=1G
#SBATCH --array=1-157

eval "$(conda shell.bash hook)"
conda activate gapseq-dev
gapseq=opt/gapseq/./gapseq

file=$(ls *.faa | sed -n ${SLURM_ARRAY_TASK_ID}p)
$gapseq doall "$file" ./TSBmed.csv Bacteria
```

### Using amino acid speed up the process
- But still don't know if I can add -K to quicken the process further?

**Comment by Waschina** [comment]
The option `-K` should work for `gapseq doall` since commit 74782d3 .
