### ISSUE TITLE
Question about gap-filling medium

### ISSUE THREAD

**Issue by altaiii** [jotech/gapseq#80]
Hello,

I'm trying to use gapfill with my custom-made medium.
I've seen that file format for medium was like (compounds,name,maxFlux).
May I ask how I can get maxFlux numbers?

Thank you in advance.

> for bug reports and errors please report the output of: ./gapseq test

**Comment by Waschina** [comment]
Hi,

the maxFlux values correspond to the (potential) maximum uptake rates of the nutrient by the organism. The unit is `mmol/hr/gDW` (mmol per hour and per gram dry weight).

As an example: The maximum uptake rate of Glucose by _Salmonella typhimurium_ ranges from 7.6 to 21.6 mmol/hr/dDW ([link](https://bionumbers.hms.harvard.edu/bionumber.aspx?id=109672&ver=3&trm=glucose+uptake+rate&org=)).

Hope this helps

**Comment by altaiii** [comment]
@Waschina 
Thank you for your explanation. It’s definitely helpful. 
However, what if a maxflux is unknown for my target metabolites or organisms? In that case, what can I do?

**Comment by altaiii** [comment]
@Waschina Can I also ask one more thing?
How the compound composition of media gets determined when it's not provided in KOMODO (DB for known media)?

**Comment by Waschina** [comment]
Hi @altaiii ,

**maxFlux values if no experimental information is available for the organism-compound-combination**

This is unfortunately usually the case. I think (please everyone correct me if I am wrong) that the metabolic modelling community does not follow a standardized way to deal with this lack of knowledge. However, what is commonly done is that experimental data on maximum uptake rates from a few model organisms is propagated to non-model organisms. Simply said, since the maximum uptake rate of Glucose in the Escherichia-Shigella genus has been estimated to range between 6 and 18.5 mmol/gDW/hr, many researchers use this also as maxFlux for Glucose or other potential main Carbon+Energy sources in their in-silico growth/gapfill media formulations. Another common 'reference point' is the maximum uptake rate of oxygen, which [has experimentally been estimated to ~27 mmol/gDW/hr](https://bionumbers.hms.harvard.edu/bionumber.aspx?id=109687&ver=5&trm=oxygen+uptake+rate&org=).

That said, the definition of maxFlux (or better: lower bounds for the exchange reactions) is one crucial source of uncertainty in genome-scale metabolic modelling. I highly recommend [this recent article ](https://doi.org/10.1186/s13059-021-02289-z)by Bernstein, Sulheim, Almaas and Segrè in Genome Biology; where this and other sources of uncertainty are discussed.

Concerning your second question: You may find [this article](https://doi.org/10.1371/journal.pone.0236890) by @maringos helpful, which exactly addresses this question.

Best wishes
Silvio

**Comment by Midnighter** [comment]
Depending on your use-case, you can also set the uptake rate of your carbon source to 1 mmol / gCDW / h. The optimal growth or production rate is then directly the flux yield. So if you are not interested in replicating experimental replication but rather metabolic engineering this may be just as or even more informative.
