### ISSUE TITLE
The results compared with PROKKA

### ISSUE THREAD

**Issue by Erique29** [jotech/gapseq#95]
Hi again,
I use gapseq 1.1 build 9 models of Vibrio spp., and I find some pathways (e.g., L-phenylalanine degradation III) existing in two of them. I made a further comparison and find the difference in the pathway was one reaction, PHENYLPYRUVATE-DECARBOXYLASE-RXN according to '-all-Pathways.tbl'. Then I extract the sequence of PHENYLPYRUVATE-DECARBOXYLASE-RXN according to '-all-Reaction.tbl'. Then I find the name of this gene in PROKKA annotation result, named Pyruvate dehydrogenase E1 component subunit alpha. Here's the weird thing. I search this name in other 7 PROKKA result and find that this gene is present in 5 of them. Can you help me with this problem? I want to knockout some genes to verify the gene function, and hope Gapseq can help me find the differential gene! 
Thanks!

**Comment by Waschina** [comment]
Hi @Erique29,

that seems to be an interesting case. It could be that the PHENYLPYRUVATE-DECARBOXYLASE-RXN ([EC 4.1.1.43](https://metacyc.org/META/NEW-IMAGE?object=PHENYLPYRUVATE-DECARBOXYLASE-RXN&redirect=T)) is a false positive hit and that the gene is actually associated part of the pyruvate dehydrogenase ([EC 1.2.4.1](https://metacyc.org/META/NEW-IMAGE?type=REACTION&object=RXN0-1134)) E1 component. Could you maybe check in your `-all-Reactions.tbl` if the same genome region is associated with both reactions?

Concerning the discrepancy to PROKKA: This can happen since prokka and gapseq are using different approaches to find and annotate genes. Also the sequence similarity cutoffs for hits might differ between the tools. With gapseq you could try to reduce this cutoff values from bitscore 200 to a lower value (say 150), e.g. for the pathway "L-phenylalanine degradation III)"

./gapseq find -p PWY-5079 -b 150 <genome.fna.gz>

**Comment by Erique29** [comment]
Hi @Waschina ,
I used the bitscore 150 to find the pathway "L-phenylalanine degradation III)", and I find the same result with PROKKA! I knew what caused this result. Thanks! 
If I use a lower value, will it lead to inaccurate forecasts? If I want to find the differential genes associated with the metabolic pathway, what bitscore would you recommend?  If I use a lower value, will it lead to inaccurate forecasts?
Best wishes
Erique

**Comment by Erique29** [comment]
Thanks for your support!
