### ISSUE TITLE
hardcoded temp file directory location

### ISSUE THREAD

**Issue by nick-youngblut** [jotech/gapseq#98]
At least for `gapseq find` the temporary file location is hardcoded:

```
# tmp working directory
tmpdir=$(mktemp -d)
echo $tmpdir
cd $tmpdir
```

...which can result in the user completely filling up `/tmp/` in a linux OS and thereby locking up the system for all users

**Comment by jotech** [comment]
Hello @nick-youngblut,
actually I think you missed the next line:
https://github.com/jotech/gapseq/blob/030008561ede1631a082065549c960dd5c389581/src/gapseq_find.sh#L194-L197
`trap` is removing the temporary files on exit. Thus, there shouldn't be any overflow of `/tmp`!
The only case I can imaging is that when the script fails then the temporary files persist (until removed by the system) which is useful for debugging. Could you elaborate what happened in your case?

On top, I wouldn't call this hardcoded because this is a system command creating temporary files in a randomly named folder that is deleted automatically after reboot. At least from my perspective, this is the usual way to handle temporary files. What is your recommendation here?

**Comment by nick-youngblut** [comment]
I see that the temp files are removed, if the job isn't killed/fails prior to `trap 'rm -rf "$tmpdir"' EXIT`. 

If `gapseq` generates a non-trivial number and/or total size of temp files, then this can still fill up `/tmp/`, if `/tmp/` is already rather full due to other running processes (or just a build-up of old files). 

`/tmp/` works well for small numbers of small-sized files, but it seems that gapseq generates a non-trivial amount of temp files in `/tmp/`. It would be helpful to all the user to specify the location of the temp output directory (eg., a large, all SSD file system).

**Comment by jotech** [comment]
alright thank you for the clarification!
I added a parameter `-T` that should handle this case:
```
./gapseq find -p PCEDEG-PWY -T ~/mytempdir toy/myb71.fna.gz
```
You you give it a try?

**Comment by nick-youngblut** [comment]
Thanks for adding the feature! 

>You you give it a try?

My institute doesn't have access to the full version of CPLEX, so we've shifted priorities to other research. Too bad that IBM doesn't actually make CPLEX available to all academic researchers.

**Comment by jotech** [comment]
ok the lp solver is another issue. but gapseq should also work with glpk! feel free to open another issue for further solver problems
